import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import { interSans, ivyPrestoDisplay, ivyPrestoHeadline } from "./fonts/font";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={clsx(
					interSans.variable,
					ivyPrestoDisplay.variable,
					ivyPrestoHeadline.variable,
					"antialiased",
				)}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
